### PR TITLE
pass file pattern to sasslint program

### PR DESCRIPTION
**Pull request by jalet**

### CODE REVIEW

**Comment by jalet** [comment]
Ping @emiloberg @marreman

**Comment by emiloberg** [comment]
Good catch! But maybe `if` it so that it uses the default path if no path is given in javascript-env config?

**Comment by jalet** [comment]
@emiloberg we don't do that for eslint, so I think we should be consistent about enforcing the user to specify the pattern.

**Comment by emiloberg** [comment]
👍

**Pull request merged**
