### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by jalet**
- React 15.4
- ReactDOM 15.4
- Webpack 2

Lets do it!

### CODE REVIEW

**Comment by jalet** [comment]
Ping @iZettle/web

**Comment by janneh** [comment]
giphy 11

**Comment by jalet** [comment]
There is currently a known issue with hot reloading, are we fine with that for now?

**Comment by janneh** [comment]
Fine with the error, fine with skipping hot reloading?

**Comment by jalet** [comment]
What error do you mean?

**Comment by janneh** [comment]
Sorry... Me beign unclear too
```
There is currently a known issue with hot reloading, are we fine with that for now?
```
Just wondered what you suggested here?

**Comment by jalet** [comment]
aha, dooh!

Are we fine with skipping hot reload for now? And then tak another stab at it another time.

**Comment by janneh** [comment]
I all for that. Let's leave it for now...

**Comment by jalet** [comment]
🎯

**Pull request merged**
