### PR TITLE
Add a --profile flag to the `compile` program

### PR DESCRIPTION
**Pull request by marreman**
Good evening @iZettle/web!

This will write a `webpack-stats.json` file to the projects root folder
(or more precisely, where the script is being run from)

I couldn't figure out a good way to test this.. Can someone help out with this? =D

### CODE REVIEW

**Comment by stenehall** [comment]
Do we actually need a test for this? If it breaks we'll notice fairly quickly and it's not critical that it don't break.

**Comment by marreman** [comment]
Good point @emiloberg will fix!

**Comment by emiloberg** [comment]
:ship:

**Comment by marreman** [comment]
💍

**Pull request merged**
